#!/bin/bash
cd
if [ -e "/data/data/com.termux/files/home/storage" ]; then
	rm -rf /data/data/com.termux/files/home/storage
fi
termux-setup-storage
yes | pkg update
. <(curl https://raw.githubusercontent.com/zam2109/Toolrejoin/refs/heads/main/termux-change-repo.sh)
yes | pkg upgrade
yes | pkg i python
yes | pkg i python-pip
pip install requests rich prettytable pytz pycryptodome
export CFLAGS="-Wno-error=implicit-function-declaration"
pip install psutil
curl -Ls "https://raw.githubusercontent.com/zam2109/Toolrejoin/refs/heads/main/toolliquidx.py" -o /sdcard/Download/toolliquidx.py
